[build]
# Build configuration
buildCommand = "pip install -r requirements.txt"

[deploy]
# Start command
startCommand = "python app.py"

# Environment variables
[variables]
# These can be set in the Railway dashboard as well
RAILWAY_ENVIRONMENT = "production"
UPLOAD_PATH = "/app/uploads"

# Volume configuration for persistent file storage
[[volumes]]
name = "model-uploads"
mountPath = "/app/uploads"
size = "5GB"  # Adjust size as needed
